/**
 * Canonical language ordering for matrix views.
 *
 * Respects D&M 2002 ordering for the 11 classic languages, the poly succinctness
 * DAG, quasi-poly edges (when reverse is not poly), and unknown-poly-quasi edges.
 * Generated by scripts/find-topo-order.ts to minimize non-red cells in the lower
 * triangle of the succinctness matrix.
 *
 * Languages not in this map are appended alphabetically.
 */
export const CANONICAL_ORDER: Record<string, number> = {
	'lang_5bf00851': 0, // NNF
	'lang_3bebcab7': 1, // DNNF
	'lang_1df07cc3': 2, // nFBDD
	'lang_b13b0d78': 3, // SDNNF
	'lang_6c130090': 4, // d-DNNF
	'lang_d24efe0e': 5, // nOBDD
	'lang_4e62a038': 6, // uFBDD
	'lang_ea9b5299': 7, // d-SDNNF
	'lang_981b62f0': 8, // dec-DNNF
	'lang_684b1ca7': 9, // FBDD
	'lang_c2df8c2b': 10, // uOBDD
	'lang_1afefbe2': 11, // SDD
	'lang_83e3b023': 12, // cSDD
	'lang_0f27d539': 13, // dec-SDNNF
	'lang_b9d72a7c': 14, // OBDD
	'lang_d69995dd': 15, // OBDD<
	'lang_4c204bf3': 16, // DNF
	'lang_89649e36': 17, // CNF
	'lang_27fffab2': 18, // PI
	'lang_6ae90adc': 19, // IP
	'lang_e02902d0': 20, // MODS
	'lang_8f666aa0': 21, // ANF
	'lang_bb65ddb5': 22, // BDD
	'lang_3c803ba1': 23, // SDNNF_T
	'lang_91f812d0': 24, // d-SDNNF_T
	'lang_9c84a267': 25, // SDD_T
	'lang_82fa749e': 26, // cSDD_T
	'lang_4ae03bc8': 27 // dec-SDNNF_<
};

/**
 * Compare two language IDs by canonical order, with alphabetical fallback.
 * @param getName - function to get a language's display name from its ID
 */
export function compareByCanonicalOrder(
	a: string,
	b: string,
	getName: (id: string) => string
): number {
	const pa = CANONICAL_ORDER[a] ?? 1000;
	const pb = CANONICAL_ORDER[b] ?? 1000;
	if (pa !== pb) return pa - pb;
	return getName(a).localeCompare(getName(b));
}
