import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../..');
const contributionPath = path.join(rootDir, 'contribution.json');
const outputPath = path.join(rootDir, 'src/lib/data/pending-contribution.js');

function readContribution(): unknown {
  if (!fs.existsSync(contributionPath)) {
    throw new Error('contribution.json was not found.');
  }
  const raw = fs.readFileSync(contributionPath, 'utf8');
  if (!raw.trim()) {
    throw new Error('contribution.json is empty.');
  }
  return JSON.parse(raw);
}

function emitModule(payload: unknown): string {
  const serialized = JSON.stringify(payload, null, 2);
  return [
    '// Auto-generated by generate-contribution.ts',
    '// This file captures the latest submission payload for reviewers.',
    `export const pendingContribution = ${serialized};`,
    'export default pendingContribution;',
    ''
  ].join('\n');
}

try {
  console.log('Writing pending contribution module...');
  const payload = readContribution();
  const moduleSource = emitModule(payload);
  fs.writeFileSync(outputPath, moduleSource, 'utf8');
  console.log(`✅ pending-contribution.js updated (${outputPath})`);
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  console.error('\n❌ Unable to generate contribution module:', message);
  process.exit(1);
}
