import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { initialGraphData, getAllEdgeFilters, getAllLanguageFilters } from '../src/lib/data/index.js';
import { applyFiltersWithParams, computeEffectiveFilterState } from '../src/lib/filter-utils.js';
import { createLatexExport } from '../src/lib/utils/latex-export.js';
import type { ViewMode } from '../src/lib/types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const docsDir = path.join(__dirname, '..', 'docs');
const languageFilters = getAllLanguageFilters();
const edgeFilters = getAllEdgeFilters();

const EXPORTS: Array<{ viewMode: ViewMode; title: string; filename: string }> = [
  { viewMode: 'graph', title: 'Tractable Circuit Zoo Graph', filename: 'zoo-graph.tex' },
  { viewMode: 'succinctness', title: 'Tractable Circuit Zoo: Succinctness Table', filename: 'zoo-succinctness-table.tex' },
  { viewMode: 'queries', title: 'Tractable Circuit Zoo: Query Table', filename: 'zoo-queries-table.tex' },
  { viewMode: 'transforms', title: 'Tractable Circuit Zoo: Transformation Table', filename: 'zoo-transformations-table.tex' }
];

function standaloneDocument(title: string, fragment: string, isGraph: boolean): string {
  const body = isGraph
    ? ['\\begin{center}', fragment, '\\end{center}'].join('\n')
    : fragment;
  return [
    '% =============================',
    '% Tractable Circuit Zoo - LaTeX export',
    '% Auto-generated by scripts/generate-latex-export-docs.ts',
    '% Regenerate with: npm run generate:latex-exports',
    '% =============================',
    '\\documentclass[11pt]{article}',
    '\\usepackage[margin=.8in]{geometry}',
    '\\usepackage{amsmath,amssymb}',
    '\\usepackage{graphicx}',
    '\\usepackage{tikz}',
    '\\usetikzlibrary{arrows.meta,shapes.geometric}',
    '',
    '\\begin{document}',
    '\\section*{' + title + '}',
    body,
    '\\end{document}',
    ''
  ].join('\n');
}

for (const item of EXPORTS) {
  const filterState = computeEffectiveFilterState(languageFilters, edgeFilters, item.viewMode, new Map());
  const data = applyFiltersWithParams(
    initialGraphData,
    languageFilters,
    edgeFilters,
    filterState,
    item.viewMode
  );
  const fragment = createLatexExport(item.viewMode, data).content;
  fs.writeFileSync(
    path.join(docsDir, item.filename),
    standaloneDocument(item.title, fragment, item.viewMode === 'graph'),
    'utf8'
  );
}

console.log('Wrote standalone LaTeX exports to docs/.');
