/-
  KCMap — Root module for the Knowledge Compilation Map formalization.

  Imports all sub-modules so that `lake build` typechecks the entire project.
  The Proofs file is auto-generated by `npm run generate-lean`.
-/
import KCMap.Basic
import KCMap.Proofs
