/-
  TCZ — Root module for the Tractable Circuit Zoo formalization.

  Imports all sub-modules so that `lake build` typechecks the entire project.
  The Proofs file is auto-generated by `npm run generate-lean`.
-/
import TCZ.Basic
import TCZ.Proofs
